server:
  port: 9015
spring:
  application:
    name: hystrix-consumer-feign-turbine
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8761
feign:
  hystrix:
    enabled: true
logging:
  level:
    xyz.wongs.service.ProviderService: debug
management:
  port: 9110
turbine:
  app-config:   hystrix-consumer-feign-factory
  cluster-name-expression: "default"
  combine-host-port: true
