spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false
    driverClassName:  com.mysql.jdbc.Driver
    username: root
    passwd: 123456
    initialSize: 10
    minIdle: 10
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: false
server:
  port: 8080
