server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
        show_sql: true
  redis:
    host: localhost
    port: 6379
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: -1
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1

flyway:
  baselineOnMigrate: true
  locations: classpath:/db
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    appname: provider-service
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    port: 8761
  client:
    service-url:
      defaultZone:  http://localhost:${eureka.server.port}/eureka/