server:
  port: 9011
spring:
  application:
    name: hystrix-consumer-feign
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8761
feign:
  hystrix:
    enabled: true
logging:
  level:
    xyz.wongs.service.ProviderService: debug
