server:
  port: 9010
spring:
  application:
    name: hystrix-consumer-ribbon
eureka:
  client:
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
    port: 8761
management:
  security:
    enabled:  false
#management:
endpoints:
  health:
    sensitive: false