server:
  port: 10001
spring:
  application:
    name: api-gateway-zuul
eureka:
  instance:
    prefer-ip-address: true
  server:
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
zuul:
  routes:
    users:
      path: /users/**
#      url: http://192.168.5.1:9001/
#      url: http://www.dangdang.com/
      stripPrefix: false
      serviceId: provider_service
    hello:
       path: /hello/**
       stripPrefix: false
       serviceId: provider_service